<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Part;

class PartSeeder extends Seeder
{
    public function run(): void
    {
        $parts = [
            [
                'id' => 'part-powerstop-z23',
                'name' => 'PowerStop Z23 Evolution Carbon-Fiber Ceramic Brake Kit',
                'brand' => 'PowerStop',
                'part_number' => 'PS-K2008-Z23',
                'category' => 'brakes',
                'price' => 199.99,
                'original_price' => 249.99,
                'rating' => 4.9,
                'reviews_count' => 842,
                'in_stock' => 18,
                'fitment_makes' => ['BMW', 'Mercedes-Benz', 'Audi', 'Toyota', 'Honda', 'Porsche'],
                'fitment_years' => '2016-2025',
                'image' => 'https://images.unsplash.com/photo-1600705722908-bab1e61c0b4d?auto=format&fit=crop&w=600&q=80',
                'description' => 'Drilled and slotted zinc-dichromate plated rotors paired with carbon-fiber infused ceramic friction pads. Low dust, zero fade under spirited driving.',
                'is_best_seller' => true,
                'badge' => '15% OFF',
            ],
            [
                'id' => 'part-kn-filter',
                'name' => 'K&N High-Flow Washable Lifetime Cold Air Filter',
                'brand' => 'K&N Engineering',
                'part_number' => 'KN-33-3111',
                'category' => 'filters',
                'price' => 54.99,
                'original_price' => 69.99,
                'rating' => 4.8,
                'reviews_count' => 1245,
                'in_stock' => 42,
                'fitment_makes' => ['All Makes', 'BMW', 'Toyota', 'Audi', 'Mercedes-Benz', 'Honda'],
                'fitment_years' => 'Universal / Model-Specific',
                'image' => 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=600&q=80',
                'description' => 'Engineered to increase horsepower and rate of acceleration while providing exceptional engine protection. Washable and reusable for 160,000 km.',
                'is_best_seller' => true,
                'badge' => 'Top Seller',
            ],
            [
                'id' => 'part-bilstein-b8',
                'name' => 'Bilstein B8 5100 Monotube High-Performance Shock Absorber',
                'brand' => 'Bilstein',
                'part_number' => 'BIL-24-186728',
                'category' => 'suspension',
                'price' => 129.99,
                'original_price' => 159.99,
                'rating' => 4.9,
                'reviews_count' => 956,
                'in_stock' => 14,
                'fitment_makes' => ['Land Rover', 'Ford', 'Toyota', 'BMW', 'Audi'],
                'fitment_years' => '2018-2025',
                'image' => 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Gas-pressure monotube damper with 46mm digressive working piston. Instantly reacts to road imperfections with razor-sharp chassis composure.',
                'is_best_seller' => true,
            ],
            [
                'id' => 'part-sealight-led',
                'name' => 'SEALIGHT X4 28,000LM Ultra 6500K LED Headlight Bulbs H11',
                'brand' => 'SEALIGHT',
                'part_number' => 'SL-H11-X4',
                'category' => 'electrical',
                'price' => 39.99,
                'original_price' => 59.99,
                'rating' => 4.7,
                'reviews_count' => 1102,
                'in_stock' => 35,
                'fitment_makes' => ['Universal Fit', 'Honda', 'Toyota', 'BMW', 'Nissan'],
                'fitment_years' => 'All Model Years',
                'image' => 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=600&q=80',
                'description' => 'True 1:1 halogen beam pattern with aircraft aluminum heat dissipation and turbo cooling fan. 400% brighter than stock bulbs.',
                'is_best_seller' => true,
                'badge' => 'Save $20',
            ],
            [
                'id' => 'part-flowmaster-muffler',
                'name' => 'Flowmaster Super 44 High-Flow Chambered Exhaust Muffler',
                'brand' => 'Flowmaster',
                'part_number' => 'FM-942548',
                'category' => 'engine',
                'price' => 89.99,
                'original_price' => 119.99,
                'rating' => 4.9,
                'reviews_count' => 753,
                'in_stock' => 12,
                'fitment_makes' => ['BMW', 'Ford', 'Chevrolet', 'Dodge', 'Toyota'],
                'fitment_years' => 'Universal 2.5" / 3.0"',
                'image' => 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
                'description' => 'Delivers an aggressive deep exterior rumble with patented Delta Flow technology that minimizes interior cabin resonance and backpressure.',
                'is_best_seller' => true,
            ],
            [
                'id' => 'part-rtx-revolver-rims',
                'name' => 'RTX Revolver Satin Black 18x8.5 Track Alloy Wheels (Set of 4)',
                'brand' => 'RTX Wheels',
                'part_number' => 'RTX-REV-1885',
                'category' => 'wheels',
                'price' => 719.99,
                'original_price' => 879.99,
                'rating' => 4.8,
                'reviews_count' => 632,
                'in_stock' => 8,
                'fitment_makes' => ['BMW', 'Audi', 'Mercedes-Benz', 'Toyota', 'Honda'],
                'fitment_years' => '5x112 / 5x120 Pattern',
                'image' => 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=600&q=80',
                'description' => 'Lightweight flow-formed alloy engineering, maximizing heat dissipation and brake caliper clearance while shaving unsprung rotary mass.',
                'is_best_seller' => true,
                'badge' => 'Popular',
            ],
            [
                'id' => 'part-optima-battery',
                'name' => 'OPTIMA RedTop High-Performance 800 CCA AGM Battery',
                'brand' => 'Optima',
                'part_number' => 'OPT-RED-3478',
                'category' => 'electrical',
                'price' => 259.99,
                'original_price' => 289.99,
                'rating' => 4.9,
                'reviews_count' => 512,
                'in_stock' => 16,
                'fitment_makes' => ['All Makes', 'Porsche', 'BMW', 'Land Rover', 'Tesla'],
                'fitment_years' => 'Universal Group 34/78',
                'image' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=80',
                'description' => 'SpiralCell design provides 15 times more vibration resistance and up to 3 times longer life than standard flooded automotive batteries.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-bosch-sparkplugs',
                'name' => 'Bosch Double Platinum Fine Wire Spark Plug (Set of 6)',
                'brand' => 'Bosch',
                'part_number' => 'BSH-FR7DPP33X',
                'category' => 'engine',
                'price' => 52.99,
                'original_price' => 65.0,
                'rating' => 4.9,
                'reviews_count' => 884,
                'in_stock' => 60,
                'fitment_makes' => ['BMW', 'Mercedes-Benz', 'Audi', 'Porsche', 'Toyota'],
                'fitment_years' => '2015-2025',
                'image' => 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=600&q=80',
                'description' => 'Laser welded 360-degree continuous platinum center electrode firing pin ensures pinpoint spark delivery and 3X longer service life.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-akebono-pads',
                'name' => 'Akebono ProACT Ultra-Premium Ceramic Brake Pads',
                'brand' => 'Akebono',
                'part_number' => 'AKB-ACT-295X',
                'category' => 'brakes',
                'price' => 94.99,
                'original_price' => 119.99,
                'rating' => 4.9,
                'reviews_count' => 1104,
                'in_stock' => 32,
                'fitment_makes' => ['All Makes', 'Toyota', 'Honda', 'Ford', 'BMW'],
                'fitment_years' => '2015-2025',
                'image' => 'https://images.unsplash.com/photo-1600705722908-bab1e61c0b4d?auto=format&fit=crop&w=600&q=80',
                'description' => 'Ultra-premium ceramic friction material with anodized steel backing plates for whisper-quiet, low-dust braking with OEM pedal feel.',
                'is_best_seller' => true,
                'badge' => 'Top Seller',
            ],
            [
                'id' => 'part-brembo-discs',
                'name' => 'Brembo Performance Drilled Disc Rotors (Pair)',
                'brand' => 'Brembo',
                'part_number' => 'BRE-09A678-23',
                'category' => 'brakes',
                'price' => 189.99,
                'original_price' => 239.99,
                'rating' => 4.9,
                'reviews_count' => 687,
                'in_stock' => 14,
                'fitment_makes' => ['BMW', 'Mercedes-Benz', 'Audi', 'Volkswagen', 'Porsche'],
                'fitment_years' => '2016-2025',
                'image' => 'https://images.unsplash.com/photo-1600705722908-bab1e61c0b4d?auto=format&fit=crop&w=600&q=80',
                'description' => 'Precision-drilled high-carbon rotors that stay cool under hard braking, shed water faster, and resist pad glazing.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-brembo-calipers',
                'name' => 'Brembo GT 4-Piston Caliper Upgrade Kit',
                'brand' => 'Brembo',
                'part_number' => 'BRE-GT41-6600',
                'category' => 'brakes',
                'price' => 1899.0,
                'original_price' => 2199.0,
                'rating' => 4.8,
                'reviews_count' => 214,
                'in_stock' => 4,
                'fitment_makes' => ['BMW', 'Audi', 'Ford', 'Chevrolet'],
                'fitment_years' => '2018-2025',
                'image' => 'https://images.unsplash.com/photo-1600705722908-bab1e61c0b4d?auto=format&fit=crop&w=600&q=80',
                'description' => 'Radial-mount 4-piston forged aluminium calipers with large racing pads for fade-free, repeatable track stopping power.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-castrol-brakefluid',
                'name' => 'Castrol React DOT 4 Brake Fluid (1L)',
                'brand' => 'Castrol',
                'part_number' => 'CST-RBF-DOT4',
                'category' => 'brakes',
                'price' => 24.99,
                'original_price' => 29.99,
                'rating' => 4.8,
                'reviews_count' => 932,
                'in_stock' => 75,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1600705722908-bab1e61c0b4d?auto=format&fit=crop&w=600&q=80',
                'description' => 'High-Performance DOT 4 fluid with dry boiling point of 265°C for consistent pedal feel in daily driving and track use.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-gates-belt-kit',
                'name' => 'Gates Timing Belt & Tensioner Kit',
                'brand' => 'Gates',
                'part_number' => 'GAT-TCK-200',
                'category' => 'engine',
                'price' => 129.99,
                'original_price' => 159.99,
                'rating' => 4.9,
                'reviews_count' => 1012,
                'in_stock' => 22,
                'fitment_makes' => ['Honda', 'Toyota', 'Nissan', 'Mazda', 'Subaru'],
                'fitment_years' => '2010-2024',
                'image' => 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=600&q=80',
                'description' => 'Complete timing belt kit with precision tensioner and idler pulleys — everything needed for a factory-spec timing service.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-felpro-gasket',
                'name' => 'Fel-Pro Performance Head Gasket Set',
                'brand' => 'Fel-Pro',
                'part_number' => 'FP-PHP-1988',
                'category' => 'engine',
                'price' => 79.99,
                'original_price' => 99.99,
                'rating' => 4.9,
                'reviews_count' => 456,
                'in_stock' => 18,
                'fitment_makes' => ['Chevrolet', 'Ford', 'Dodge', 'Toyota'],
                'fitment_years' => '2005-2024',
                'image' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
                'description' => 'Multi-layer steel (MLS) head gaskets with PermaDry sealing technology for the toughest engine rebuilds.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-acdelco-pistons',
                'name' => 'ACDelco Forged Performance Piston Set',
                'brand' => 'ACDelco',
                'part_number' => 'ACD-FP-4032',
                'category' => 'engine',
                'price' => 349.99,
                'original_price' => 419.99,
                'rating' => 4.7,
                'reviews_count' => 176,
                'in_stock' => 6,
                'fitment_makes' => ['GM', 'Chevrolet', 'Ford'],
                'fitment_years' => '2015-2024',
                'image' => 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
                'description' => 'CNC-forged 2618 alloy pistons rated for forced-induction builds up to 850hp with premium ring package included.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-moog-control-arms',
                'name' => 'MOOG Premium Control Arm Kit',
                'brand' => 'MOOG',
                'part_number' => 'MOG-RK620263',
                'category' => 'suspension',
                'price' => 149.99,
                'original_price' => 179.99,
                'rating' => 4.8,
                'reviews_count' => 894,
                'in_stock' => 11,
                'fitment_makes' => ['BMW', 'Toyota', 'Honda', 'Ford', 'Chevrolet'],
                'fitment_years' => '2015-2025',
                'image' => 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Problem-solver control arms with pre-installed ball joints and bushings for precise steering and alignment retention.',
                'is_best_seller' => true,
            ],
            [
                'id' => 'part-poly-bushings',
                'name' => 'Polyurethane Suspension Bushing Kit',
                'brand' => 'Prothane',
                'part_number' => 'PTH-18-1125',
                'category' => 'suspension',
                'price' => 79.99,
                'original_price' => 99.99,
                'rating' => 4.7,
                'reviews_count' => 512,
                'in_stock' => 27,
                'fitment_makes' => ['All Makes', 'BMW', 'Honda', 'Mazda'],
                'fitment_years' => '2000-2024',
                'image' => 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Performance polyurethane bushings that eliminate sloppy suspension movement and sharpen the chassis handling response.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-mevotech-balljoints',
                'name' => 'Mevotech Supreme Ball Joint Kit',
                'brand' => 'Mevotech',
                'part_number' => 'MEV-SBJ-4450',
                'category' => 'suspension',
                'price' => 49.99,
                'original_price' => 64.99,
                'rating' => 4.8,
                'reviews_count' => 633,
                'in_stock' => 38,
                'fitment_makes' => ['All Makes', 'Toyota', 'Ford', 'Chevrolet'],
                'fitment_years' => '2012-2024',
                'image' => 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=600&q=80',
                'description' => 'Greaseable, forged-steel ball joints with PTFE-coated studs for long service life and a factory-fresh ride.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-denso-alternator',
                'name' => 'Denso High-Output Alternator (220A)',
                'brand' => 'Denso',
                'part_number' => 'DEN-ALT-220',
                'category' => 'electrical',
                'price' => 249.99,
                'original_price' => 289.99,
                'rating' => 4.9,
                'reviews_count' => 388,
                'in_stock' => 9,
                'fitment_makes' => ['Toyota', 'Honda', 'BMW', 'Mercedes-Benz'],
                'fitment_years' => '2015-2025',
                'image' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=80',
                'description' => 'High-output 220A alternator engineered for higher electrical loads — audio systems, winches, and auxiliary lighting.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-bosch-starter',
                'name' => 'Bosch Professional Starter Motor',
                'brand' => 'Bosch',
                'part_number' => 'BSH-SRM-0049',
                'category' => 'electrical',
                'price' => 179.99,
                'original_price' => 209.99,
                'rating' => 4.9,
                'reviews_count' => 425,
                'in_stock' => 12,
                'fitment_makes' => ['All Makes', 'Volkswagen', 'Audi', 'Mercedes-Benz'],
                'fitment_years' => '2013-2024',
                'image' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=80',
                'description' => 'OEM-grade remanufactured starter motor with fully tested solenoid, planetary gear assembly, and sealed electronics.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-bosch-fuses',
                'name' => 'Bosch Standard & Mini Blade Fuse Assortment (120 pc)',
                'brand' => 'Bosch',
                'part_number' => 'BSH-FUS-120',
                'category' => 'electrical',
                'price' => 14.99,
                'original_price' => 19.99,
                'rating' => 4.8,
                'reviews_count' => 721,
                'in_stock' => 90,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=600&q=80',
                'description' => 'Everyday blade fuse assortment in a durable case — standard, mini, and low-profile sizes for repairs and replacements.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-aisin-trans-filter',
                'name' => 'AISIN Automatic Transmission Filter Kit',
                'brand' => 'AISIN',
                'part_number' => 'AIS-TF-3110',
                'category' => 'transmission',
                'price' => 39.99,
                'original_price' => 49.99,
                'rating' => 4.8,
                'reviews_count' => 358,
                'in_stock' => 30,
                'fitment_makes' => ['Toyota', 'Lexus', 'Honda', 'Nissan'],
                'fitment_years' => '2012-2024',
                'image' => 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
                'description' => 'OEM-quality filter, pan gasket, and o-rings for complete transmission service without the stealership price.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-mobil-atf',
                'name' => 'Mobil 1 Synthetic ATF Transmission Fluid (1 GAL)',
                'brand' => 'Mobil 1',
                'part_number' => 'M1-SATF-128',
                'category' => 'transmission',
                'price' => 54.99,
                'original_price' => 64.99,
                'rating' => 4.9,
                'reviews_count' => 614,
                'in_stock' => 48,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'Dexron VI / Mercon V / SP-III',
                'image' => 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
                'description' => 'Full-synthetic ATF engineered for smooth shifts, superior friction durability, and extended transmission life.',
                'is_best_seller' => true,
            ],
            [
                'id' => 'part-luk-clutch-kit',
                'name' => 'LUK Clutch Kit (Disc, Pressure Plate & Release Bearing)',
                'brand' => 'LUK',
                'part_number' => 'LUK-04-213',
                'category' => 'transmission',
                'price' => 289.99,
                'original_price' => 339.99,
                'rating' => 4.9,
                'reviews_count' => 266,
                'in_stock' => 8,
                'fitment_makes' => ['Volkswagen', 'Audi', 'BMW', 'Ford'],
                'fitment_years' => '2012-2024',
                'image' => 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
                'description' => 'Complete clutch replacement kit with OE-style damped disc, pressure plate, and release bearing for smooth engagement.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-mishimoto-radiator',
                'name' => 'Mishimoto Aluminum Racing Radiator',
                'brand' => 'Mishimoto',
                'part_number' => 'MSH-MMR-88',
                'category' => 'cooling',
                'price' => 349.99,
                'original_price' => 419.99,
                'rating' => 4.9,
                'reviews_count' => 521,
                'in_stock' => 7,
                'fitment_makes' => ['Honda', 'Nissan', 'Subaru', 'BMW', 'Mazda'],
                'fitment_years' => '2002-2024',
                'image' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=600&q=80',
                'description' => '100% aluminium, 2-row cored radiator with TIG-welded tanks for maximum heat rejection and lifetime performance.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-stant-thermostat',
                'name' => 'Stant SuperStat Thermostat',
                'brand' => 'Stant',
                'part_number' => 'STA-SST-45358',
                'category' => 'cooling',
                'price' => 17.99,
                'original_price' => 22.99,
                'rating' => 4.8,
                'reviews_count' => 884,
                'in_stock' => 65,
                'fitment_makes' => ['All Makes'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=600&q=80',
                'description' => 'Fail-safe thermostat with premium wax element and bypass design that holds temperature steadier under load.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-bosch-waterpump',
                'name' => 'Bosch Engine Water Pump',
                'brand' => 'Bosch',
                'part_number' => 'BSH-WPU-6723',
                'category' => 'cooling',
                'price' => 119.99,
                'original_price' => 149.99,
                'rating' => 4.9,
                'reviews_count' => 445,
                'in_stock' => 13,
                'fitment_makes' => ['All Makes', 'BMW', 'Audi', 'Volkswagen'],
                'fitment_years' => '2010-2024',
                'image' => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=600&q=80',
                'description' => 'OEM-spec coolant pump with durable ceramic seal and precision bearings for quiet, leak-free cooling circulation.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-mobil-oil-filter',
                'name' => 'Mobil 1 Extended Performance Oil Filter',
                'brand' => 'Mobil 1',
                'part_number' => 'M1-EP-110',
                'category' => 'filters',
                'price' => 16.99,
                'original_price' => 21.99,
                'rating' => 4.9,
                'reviews_count' => 1392,
                'in_stock' => 88,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=600&q=80',
                'description' => 'Extended performance synthetic blend media filter rated for up to 32,000-km service intervals.',
                'is_best_seller' => true,
            ],
            [
                'id' => 'part-bosch-air-filter',
                'name' => 'Bosch Filtron Engine Air Filter',
                'brand' => 'Bosch',
                'part_number' => 'BSH-AF-0999',
                'category' => 'filters',
                'price' => 24.99,
                'original_price' => 29.99,
                'rating' => 4.8,
                'reviews_count' => 1022,
                'in_stock' => 54,
                'fitment_makes' => ['All Makes', 'BMW', 'Toyota', 'Ford'],
                'fitment_years' => '2014-2024',
                'image' => 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=600&q=80',
                'description' => 'High-efficiency multi-layer media air filter that protects the engine while optimizing airflow and fuel economy.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-fram-fuel-filter',
                'name' => 'FRAM SureGrip Fuel Filter',
                'brand' => 'FRAM',
                'part_number' => 'FRM-G7418',
                'category' => 'filters',
                'price' => 12.99,
                'original_price' => 16.99,
                'rating' => 4.8,
                'reviews_count' => 766,
                'in_stock' => 47,
                'fitment_makes' => ['All Makes', 'Toyota', 'Honda', 'Ford'],
                'fitment_years' => '2008-2024',
                'image' => 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=600&q=80',
                'description' => 'SureGrip fuel filter with high-dirt-holding capacity to protect fuel injectors and pumps from contamination.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-michelin-tires',
                'name' => 'Michelin Pilot Sport 4 S Tyres (Set of 4)',
                'brand' => 'Michelin',
                'part_number' => 'MCL-PS4S-25535',
                'category' => 'wheels',
                'price' => 1199.99,
                'original_price' => 1399.99,
                'rating' => 4.9,
                'reviews_count' => 943,
                'in_stock' => 6,
                'fitment_makes' => ['All Makes'],
                'fitment_years' => '255/35 R19',
                'image' => 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=600&q=80',
                'description' => 'The benchmark max-performance summer tyre — razor-sharp steering, incredible dry grip, and confidence in the wet.',
                'is_best_seller' => true,
                'badge' => 'Best Seller',
            ],
            [
                'id' => 'part-bbs-rims',
                'name' => 'BBS CH-R Graphite Alloy Rims 18" (Set of 4)',
                'brand' => 'BBS',
                'part_number' => 'BBS-CHR-18',
                'category' => 'wheels',
                'price' => 1499.99,
                'original_price' => 1799.99,
                'rating' => 4.9,
                'reviews_count' => 312,
                'in_stock' => 5,
                'fitment_makes' => ['BMW', 'Audi', 'Mercedes-Benz', 'Volkswagen'],
                'fitment_years' => '5x112 / 5x120',
                'image' => 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=600&q=80',
                'description' => 'Flow-formed lightweight aluminium rims with a stiffer rim bed and striking graphite finish — style meets strength.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-gorilla-lug-nuts',
                'name' => 'Gorilla Wheel Locks & Lug Nut Set (20 pc)',
                'brand' => 'Gorilla',
                'part_number' => 'GOR-45525-HT',
                'category' => 'wheels',
                'price' => 49.99,
                'original_price' => 59.99,
                'rating' => 4.8,
                'reviews_count' => 487,
                'in_stock' => 39,
                'fitment_makes' => ['All Makes'],
                'fitment_years' => '12mm x 1.5 / universal',
                'image' => 'https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=600&q=80',
                'description' => 'Cold-forged lug nuts with anti-theft wheel locks and unique key for total wheel security.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-floor-liners',
                'name' => 'WeatherTech All-Weather Custom Floor Liners',
                'brand' => 'WeatherTech',
                'part_number' => 'WT-FL-44121',
                'category' => 'accessories',
                'price' => 179.99,
                'original_price' => 209.99,
                'rating' => 4.9,
                'reviews_count' => 1234,
                'in_stock' => 20,
                'fitment_makes' => ['All Makes'],
                'fitment_years' => 'Model-Specific Fit',
                'image' => 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=600&q=80',
                'description' => 'Digitally measured laser-fit floor liners that trap water, mud, and snow with raised ridges for total floor protection.',
                'is_best_seller' => true,
                'badge' => 'Top Seller',
            ],
            [
                'id' => 'part-seat-covers',
                'name' => 'Katzkin Custom Leather Seat Covers',
                'brand' => 'Katzkin',
                'part_number' => 'KTZ-SC-2020',
                'category' => 'accessories',
                'price' => 899.99,
                'original_price' => 1099.99,
                'rating' => 4.8,
                'reviews_count' => 268,
                'in_stock' => 8,
                'fitment_makes' => ['All Makes'],
                'fitment_years' => 'Model-Specific Fit',
                'image' => 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=600&q=80',
                'description' => 'Full custom leather upholstery in your choice of colours and stitching with a factory-finish look.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-steering-cover',
                'name' => 'Perforated Leather Steering Wheel Cover',
                'brand' => 'MotorSeat',
                'part_number' => 'MTS-SC-14',
                'category' => 'accessories',
                'price' => 19.99,
                'original_price' => 24.99,
                'rating' => 4.6,
                'reviews_count' => 1985,
                'in_stock' => 64,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => '14-16" Wheels',
                'image' => 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=600&q=80',
                'description' => 'Anti-slip perforated leather steering wheel cover that improves grip and adds a premium touch to any cabin.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-phone-holder',
                'name' => 'Magnetic Car Phone Holder (Dashboard & Vent)',
                'brand' => 'Anker',
                'part_number' => 'ANK-MPH-01',
                'category' => 'accessories',
                'price' => 24.99,
                'original_price' => 29.99,
                'rating' => 4.7,
                'reviews_count' => 3421,
                'in_stock' => 120,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=600&q=80',
                'description' => '360° adjustable magnetic phone mount with strong N52 magnets and a pivoting ball socket for one-handed mounting.',
                'is_best_seller' => true,
            ],
            [
                'id' => 'part-dash-cam',
                'name' => '4K Ultra HD Dual Dash Camera (Front & Rear)',
                'brand' => 'VIOFO',
                'part_number' => 'VFO-A1294K',
                'category' => 'accessories',
                'price' => 199.99,
                'original_price' => 249.99,
                'rating' => 4.8,
                'reviews_count' => 1190,
                'in_stock' => 17,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=600&q=80',
                'description' => 'Sony STARVIS 4K front + 1080p rear recording with built-in GPS, Wi-Fi, and parking-guard motion detection.',
                'is_best_seller' => true,
                'badge' => 'Popular',
            ],
            [
                'id' => 'part-parking-sensors',
                'name' => 'Wireless Rear Parking Sensor System',
                'brand' => 'Cobra',
                'part_number' => 'CBR-PKS-4A',
                'category' => 'accessories',
                'price' => 89.99,
                'original_price' => 109.99,
                'rating' => 4.6,
                'reviews_count' => 743,
                'in_stock' => 21,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=600&q=80',
                'description' => '4-sensor wireless parking assist with distance display and audible beeps so every parking spot becomes easy.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-led-headlights',
                'name' => 'Philips Ultinon Pro9000 LED Headlight Kit',
                'brand' => 'Philips',
                'part_number' => 'PHP-LED-9000',
                'category' => 'accessories',
                'price' => 129.99,
                'original_price' => 159.99,
                'rating' => 4.9,
                'reviews_count' => 1667,
                'in_stock' => 29,
                'fitment_makes' => ['Universal Fit', 'Honda', 'Toyota', 'BMW'],
                'fitment_years' => 'H11/H7/HB4 Sockets',
                'image' => 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=600&q=80',
                'description' => 'Intense 4500K premium LED upgrade with active cooling fan for sharp, bright, and perfectly focused beam patterns.',
                'is_best_seller' => true,
                'badge' => 'Save $30',
            ],
            [
                'id' => 'part-car-audio',
                'name' => 'Pioneer Double-DIN Car Audio Receiver w/ Apple CarPlay',
                'brand' => 'Pioneer',
                'part_number' => 'PIO-DSM-AH2550',
                'category' => 'accessories',
                'price' => 349.99,
                'original_price' => 399.99,
                'rating' => 4.8,
                'reviews_count' => 634,
                'in_stock' => 10,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=600&q=80',
                'description' => '6.8" touchscreen receiver with Apple CarPlay, Android Auto, Bluetooth, and DSP equaliser for studio-grade sound.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-speakers',
                'name' => 'JBL 6.5" Coaxial Car Speakers (Pair)',
                'brand' => 'JBL',
                'part_number' => 'JBL-CX652-2',
                'category' => 'accessories',
                'price' => 129.99,
                'original_price' => 149.99,
                'rating' => 4.8,
                'reviews_count' => 1456,
                'in_stock' => 33,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => '6.5" / 165mm',
                'image' => 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=600&q=80',
                'description' => 'High-efficiency coaxial speakers with Edge-Driven tweeters for crisp highs, deep bass, and dynamic clarity.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-car-charger',
                'name' => 'Anker 45W Dual-Port USB-C Fast Car Charger',
                'brand' => 'Anker',
                'part_number' => 'ANK-45W-CC',
                'category' => 'accessories',
                'price' => 34.99,
                'original_price' => 39.99,
                'rating' => 4.9,
                'reviews_count' => 2876,
                'in_stock' => 95,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=600&q=80',
                'description' => 'Charge two phones at once with 45W of total USB-C/PD fast charging that can even power laptops on the move.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-air-freshener',
                'name' => 'Little Trees Premium Car Air Fresheners (6 Pack)',
                'brand' => 'Little Trees',
                'part_number' => 'LT-AF-6PK',
                'category' => 'accessories',
                'price' => 8.99,
                'original_price' => 12.99,
                'rating' => 4.7,
                'reviews_count' => 4088,
                'in_stock' => 210,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=600&q=80',
                'description' => 'Iconic scented trees in assorted fresh fragrance favourites to keep your interior smelling great for weeks.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-sunshade',
                'name' => 'Foldable Windshield Sunshade (UV Protection)',
                'brand' => 'Covercraft',
                'part_number' => 'CVC-SS-UV',
                'category' => 'accessories',
                'price' => 29.99,
                'original_price' => 39.99,
                'rating' => 4.7,
                'reviews_count' => 987,
                'in_stock' => 48,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=80',
                'description' => 'Block up to 99% of UV rays and cut interior heat dramatically with this custom-fit folding sunshade.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-wiper-blades',
                'name' => 'Bosch ICON All-Weather Wiper Blades (Pair)',
                'brand' => 'Bosch',
                'part_number' => 'BSH-ICON-PAIR',
                'category' => 'accessories',
                'price' => 41.99,
                'original_price' => 49.99,
                'rating' => 4.9,
                'reviews_count' => 2123,
                'in_stock' => 60,
                'fitment_makes' => ['All Makes'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=600&q=80',
                'description' => 'Beam-style wipers with FX dual rubber compound for a virtually streak-free, chatter-free wipe in all weather.',
                'is_best_seller' => true,
            ],
            [
                'id' => 'part-roof-rack',
                'name' => 'Thule Crossbar Roof Rack System',
                'brand' => 'Thule',
                'part_number' => 'THU-XL-450R',
                'category' => 'accessories',
                'price' => 299.99,
                'original_price' => 349.99,
                'rating' => 4.9,
                'reviews_count' => 365,
                'in_stock' => 7,
                'fitment_makes' => ['All Makes'],
                'fitment_years' => 'Universal Fit',
                'image' => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=600&q=80',
                'description' => 'Aerodynamic, wind-tunnel-tested crossbars with robust load rating — carry kayaks, bikes, and roof boxes securely.',
                'is_best_seller' => false,
            ],
            [
                'id' => 'part-cleaning-kit',
                'name' => 'Meguiar\'s Complete Car Detailing & Cleaning Kit',
                'brand' => 'Meguiar`s',
                'part_number' => 'MEG-COMPLETE-8',
                'category' => 'accessories',
                'price' => 79.99,
                'original_price' => 99.99,
                'rating' => 4.8,
                'reviews_count' => 1544,
                'in_stock' => 40,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'All Vehicles',
                'image' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=80',
                'description' => 'Complete kit including wash, wax, tyre shine, interior cleaner, microfibre towels, and applicator pads.',
                'is_best_seller' => true,
                'badge' => 'Save $20',
            ],
            [
                'id' => 'part-jump-starter',
                'name' => 'NOCO GB40 1000A Lithium Jump Starter + Power Bank',
                'brand' => 'NOCO',
                'part_number' => 'NOC-GB40-6A',
                'category' => 'accessories',
                'price' => 99.99,
                'original_price' => 129.99,
                'rating' => 4.9,
                'reviews_count' => 1833,
                'in_stock' => 22,
                'fitment_makes' => ['Universal Fit'],
                'fitment_years' => 'Up to 6L Gas / 3L Diesel',
                'image' => 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=600&q=80',
                'description' => 'Jump-start a dead battery in seconds plus power phones and tablets with 1000A and USB charging — safe and spark-proof.',
                'is_best_seller' => true,
            ],
        ];

        foreach ($parts as $part) {
            Part::updateOrCreate(
                ['id' => $part['id']],
                $part
            );
        }
    }
}

